run_id: 100
GPU_map:
  0: "22GiB"
prompt_modes: ["honest"]
prompt_modes_inference: []
user_prompt: "Is the following statement true or false?"
prefix_prompt: ""
seq_positions: [-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1]
offload_folder: "offload_1"
dataset_begin: 0
dataset_end: 275